### ISSUE TITLE
127.0.0.1:9000 returns: Something broke

### ISSUE THREAD

**Issue by highcup** [noirscape/e621-docker#2]
With a fresh clone and setup e621 does not work when hitting http:127.0.0.1:9000 or http://e621ng.local:9000 with the local hosts file pointing to 127.0.0.1. All that is returned is a 500 error and text saying: "Something broke". Is there something that I am missing? The following contains how everything is setup

Commit: 418efb4d147921e93c330531a214e469b6fc41d5
Operating System: Ubuntu 20.04
Kernel: Linux 69-dt 5.4.0-45-generic
Docker Version: 19.03.12

Log from docker
```
core_1       | 03:10:34 unicorn	| /app/app/controllers/application_controller.rb:118: warning: Using the last argument as keyword parameters is deprecated
sql_1        | 2020-09-10 03:10:34.841 UTC [38] ERROR:  relation "exception_logs" does not exist at character 454
sql_1        | 2020-09-10 03:10:34.841 UTC [38] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
sql_1        | 	       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
sql_1        | 	       c.collname, col_description(a.attrelid, a.attnum) AS comment
sql_1        | 	  FROM pg_attribute a
sql_1        | 	  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
sql_1        | 	  LEFT JOIN pg_type t ON a.atttypid = t.oid
sql_1        | 	  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
sql_1        | 	 WHERE a.attrelid = '"exception_logs"'::regclass
sql_1        | 	   AND a.attnum > 0 AND NOT a.attisdropped
sql_1        | 	 ORDER BY a.attnum
sql_1        | 	
core_1       | 03:10:34 unicorn	| 172.18.0.7 - - [10/Sep/2020:03:10:34 UTC] "GET / HTTP/1.0" 500 373
core_1       | 03:10:34 unicorn	| - -> /
core_1       | 03:10:35 unicorn	| /app/app/controllers/application_controller.rb:118: warning: Using the last argument as keyword parameters is deprecated
sql_1        | 2020-09-10 03:10:35.011 UTC [38] ERROR:  relation "exception_logs" does not exist at character 454
sql_1        | 2020-09-10 03:10:35.011 UTC [38] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
sql_1        | 	       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
sql_1        | 	       c.collname, col_description(a.attrelid, a.attnum) AS comment
sql_1        | 	  FROM pg_attribute a
sql_1        | 	  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
sql_1        | 	  LEFT JOIN pg_type t ON a.atttypid = t.oid
sql_1        | 	  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
sql_1        | 	 WHERE a.attrelid = '"exception_logs"'::regclass
sql_1        | 	   AND a.attnum > 0 AND NOT a.attisdropped
sql_1        | 	 ORDER BY a.attnum
sql_1        | 	
core_1       | 03:10:35 unicorn	| 172.18.0.7 - - [10/Sep/2020:03:10:34 UTC] "GET /assets/application.css HTTP/1.0" 500 373
core_1       | 03:10:35 unicorn	| http://e621ng.local:9000/ -> /assets/application.css
```

.env
```
MOUNT_SQL=./data/sql
MOUNT_LOG=./data/log
MOUNT_DATA=./data/data
MOUNT_ASSETS=./data/assets
MOUNT_ES=./data/es
NGINX_LOGS_MOUNT=./data/nginx

# This is the frontend port, aka the part that will be exposed
NGINX_PORT=9000

# Use `openssl rand -base64 32` and paste the output here
SECRET_TOKEN=ktw+rG8UZVKPDPg3bvoqS9G6LOrs/nW18DzZJh+T7vU=
SECRET_KEY=ktw+rG8UZVKPDPg3bvoqS9G6LOrs/nW18DzZJh+T7vU=

# Skips cloudflare IP check, useful for offline uploads
SKIP_CLOUDFLARE_CHECK=
```

core/danbooru_local_config.rb
```
module Danbooru
  class CustomConfiguration < Configuration
    def safe_mode
        false
    end
    # Define your custom overloads here
  end
end
```

ls -l data/
```
total 24
drwxrwxrwx  2 root root 4096 Sep  2 12:59 assets
drwxrwxrwx  2 root root 4096 Sep  2 13:09 data
drwxrwxrwx  3 root root 4096 Sep  2 13:08 es
drwxrwxrwx  2 root root 4096 Sep  2 13:09 log
drwxrwxrwx  2 root root 4096 Sep  2 12:59 nginx
drwx------ 19   70 root 4096 Sep  9 22:20 sql
```

**Comment by noirscape** [comment]
Could you try running `docker-compose run --rm core rake db:migrate` ?

**Comment by highcup** [comment]
I ran the command ```docker-compose run --rm core rake db:migrate``` and got this output.

```
Starting e621-docker_sql_1       ... done
Starting e621-docker_redis_1     ... done
Starting e621-docker_memcached_1 ... done
Starting e621-docker_es_1        ... done
DEPRECATION WARNING: ActionDispatch::Http::ParameterFilter is deprecated and will be removed from Rails 6.1. Use ActiveSupport::ParameterFilter instead. (called from <main> at /app/lib/tasks/maintenance.rake:1)
== 20130424121410 AddNameToPoolVersions: migrating ============================
-- execute("set statement_timeout = 0")
   -> 0.0007s
-- add_column(:pool_versions, :name, :string, {})
   -> 0.0509s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant AddNameToPoolVersions::PoolVersion
Did you mean?  PoolVersionsHelper
/app/db/migrate/20130424121410_add_name_to_pool_versions.rb:5:in `change'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:828:in `exec_migration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:811:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:810:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1002:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1061:in `up'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1036:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'

Caused by:
NameError: uninitialized constant AddNameToPoolVersions::PoolVersion
Did you mean?  PoolVersionsHelper
/app/db/migrate/20130424121410_add_name_to_pool_versions.rb:5:in `change'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:828:in `exec_migration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:811:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:810:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1002:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1061:in `up'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1036:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by noirscape** [comment]
Issue reproducible.

Appears to have been introduced in https://github.com/noirscape/e621-docker/commit/6b1ea2c8befc960f79a55b6cd19ac9425d7bf390 .

**Comment by noirscape** [comment]
Issue should be fixed @highcup . Could you try repulling/rebuilding your containers?

You'll also want to remove your existing data folders, I'm afraid it's not usable.

**Comment by highcup** [comment]
b1ca793f5d7f37b35572f1f2feb1d424eecd6d8a fixes the problem. I can now access the home page and everything. Thank you for the fix.

**Comment by noirscape** [comment]
Good to hear.
